-- lumae Earth Cocoa — GENERATED (npm run build:nvim). Do not hand-edit.
-- Source of truth: specs/code-syntax.md section 5 (role map).
-- Author: Mae C.
---@diagnostic disable: undefined-global
vim.cmd("highlight clear")
vim.o.background = "dark"
vim.g.colors_name = "lumae-earth-cocoa"
local hl = vim.api.nvim_set_hl
hl(0, "@attribute", { fg = "#cfac5c" })
hl(0, "@boolean", { fg = "#eb9c58" })
hl(0, "@comment", { fg = "#716659", italic = true })
hl(0, "@constant", { fg = "#eb9c58" })
hl(0, "@constant.builtin", { fg = "#eb9c58" })
hl(0, "@constructor", { fg = "#82b5ed" })
hl(0, "@function", { fg = "#82b5ed" })
hl(0, "@function.builtin", { fg = "#82b5ed" })
hl(0, "@function.call", { fg = "#82b5ed" })
hl(0, "@function.macro", { fg = "#f18eac" })
hl(0, "@function.method", { fg = "#82b5ed" })
hl(0, "@function.method.call", { fg = "#82b5ed" })
hl(0, "@keyword", { fg = "#d693ea" })
hl(0, "@keyword.conditional", { fg = "#d693ea" })
hl(0, "@keyword.coroutine", { fg = "#d693ea" })
hl(0, "@keyword.directive", { fg = "#d693ea" })
hl(0, "@keyword.exception", { fg = "#d693ea" })
hl(0, "@keyword.function", { fg = "#d693ea" })
hl(0, "@keyword.import", { fg = "#d693ea" })
hl(0, "@keyword.operator", { fg = "#d693ea" })
hl(0, "@keyword.repeat", { fg = "#d693ea" })
hl(0, "@keyword.return", { fg = "#d693ea" })
hl(0, "@label", { fg = "#82b5ed" })
hl(0, "@lsp.type.class", { fg = "#cfac5c" })
hl(0, "@lsp.type.comment", { fg = "#716659", italic = true })
hl(0, "@lsp.type.decorator", { fg = "#f18eac" })
hl(0, "@lsp.type.enum", { fg = "#cfac5c" })
hl(0, "@lsp.type.enumMember", { fg = "#5dc5bd" })
hl(0, "@lsp.type.function", { fg = "#82b5ed" })
hl(0, "@lsp.type.interface", { fg = "#cfac5c" })
hl(0, "@lsp.type.keyword", { fg = "#d693ea" })
hl(0, "@lsp.type.macro", { fg = "#f18eac" })
hl(0, "@lsp.type.method", { fg = "#82b5ed" })
hl(0, "@lsp.type.namespace", { fg = "#cfac5c" })
hl(0, "@lsp.type.number", { fg = "#eb9c58" })
hl(0, "@lsp.type.operator", { fg = "#5dc5bd" })
hl(0, "@lsp.type.parameter", { fg = "#f09584", italic = true })
hl(0, "@lsp.type.property", { fg = "#f0e8e0" })
hl(0, "@lsp.type.regexp", { fg = "#f18eac" })
hl(0, "@lsp.type.string", { fg = "#68c892" })
hl(0, "@lsp.type.type", { fg = "#cfac5c" })
hl(0, "@lsp.type.typeParameter", { fg = "#cfac5c" })
hl(0, "@lsp.type.variable", { fg = "#f0e8e0" })
hl(0, "@markup.link", { fg = "#82b5ed" })
hl(0, "@markup.link.label", { fg = "#5dc5bd" })
hl(0, "@markup.link.url", { fg = "#cccffe" })
hl(0, "@module", { fg = "#cfac5c" })
hl(0, "@number", { fg = "#eb9c58" })
hl(0, "@number.float", { fg = "#eb9c58" })
hl(0, "@operator", { fg = "#5dc5bd" })
hl(0, "@property", { fg = "#82b5ed" })
hl(0, "@punctuation.bracket", { fg = "#bbaea1" })
hl(0, "@punctuation.delimiter", { fg = "#bbaea1" })
hl(0, "@punctuation.special", { fg = "#bbaea1" })
hl(0, "@string", { fg = "#68c892" })
hl(0, "@string.escape", { fg = "#f18eac" })
hl(0, "@string.regexp", { fg = "#f18eac" })
hl(0, "@string.special.symbol", { fg = "#f09584" })
hl(0, "@tag", { fg = "#d693ea" })
hl(0, "@tag.attribute", { fg = "#cfac5c" })
hl(0, "@tag.delimiter", { fg = "#bbaea1" })
hl(0, "@type", { fg = "#cfac5c" })
hl(0, "@type.builtin", { fg = "#cfac5c" })
hl(0, "@type.definition", { fg = "#cfac5c" })
hl(0, "@variable", { fg = "#f0e8e0" })
hl(0, "@variable.builtin", { fg = "#f09584" })
hl(0, "@variable.member", { fg = "#f0e8e0" })
hl(0, "@variable.parameter", { fg = "#f09584", italic = true })
hl(0, "Cursor", { fg = "#16120f", bg = "#f18eac" })
hl(0, "CursorLine", { bg = "#322b25" })
hl(0, "CursorLineNr", { fg = "#cccffe" })
hl(0, "DapBreakpoint", { fg = "#f09584" })
hl(0, "DiagnosticError", { fg = "#f09584" })
hl(0, "DiagnosticHint", { fg = "#5dc5bd" })
hl(0, "DiagnosticInfo", { fg = "#5dc5bd" })
hl(0, "DiagnosticUnderlineError", { sp = "#f09584", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#5dc5bd", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#5dc5bd", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#cfac5c", undercurl = true })
hl(0, "DiagnosticWarn", { fg = "#cfac5c" })
hl(0, "DiffAdd", { bg = "#68c892" })
hl(0, "DiffChange", { bg = "#82b5ed" })
hl(0, "DiffDelete", { bg = "#f09584" })
hl(0, "EndOfBuffer", { fg = "#16120f" })
hl(0, "FloatBorder", { fg = "#716659", bg = "#322b25" })
hl(0, "GitSignsAdd", { fg = "#68c892" })
hl(0, "GitSignsChange", { fg = "#82b5ed" })
hl(0, "GitSignsDelete", { fg = "#f09584" })
hl(0, "IncSearch", { fg = "#16120f", bg = "#f09584" })
hl(0, "LineNr", { fg = "#716659" })
hl(0, "MatchParen", { bg = "#52493f", bold = true })
hl(0, "Normal", { fg = "#f0e8e0", bg = "#16120f" })
hl(0, "NormalFloat", { fg = "#f0e8e0", bg = "#322b25" })
hl(0, "Pmenu", { fg = "#f0e8e0", bg = "#322b25" })
hl(0, "PmenuSel", { fg = "#16120f", bg = "#cccffe" })
hl(0, "Search", { fg = "#16120f", bg = "#5dc5bd" })
hl(0, "SignColumn", { bg = "#16120f" })
hl(0, "StatusLine", { fg = "#f0e8e0", bg = "#322b25" })
hl(0, "Visual", { bg = "#52493f" })
hl(0, "WinSeparator", { fg = "#52493f" })
