-- if true then return {} end -- WARN: REMOVE THIS LINE TO ACTIVATE THIS FILE

-- AstroUI provides the basis for configuring the AstroNvim User Interface
-- Configuration documentation can be found with `:h astroui`
-- NOTE: We highly recommend setting up the Lua Language Server (`:LspInstall lua_ls`)
--       as this provides autocomplete and documentation while editing

-- lumae: follow whichever flavour `npm run theme:apply` last set. Read at
-- startup only -- running instances keep their colours until restarted, by
-- design. The colourschemes themselves live in colors/lumae-<flavor>.lua and
-- are generated by the lumae repo (`npm run build:nvim && npm run theme:sync`).
local function lumae_colorscheme()
  local state = vim.fn.expand "~/.local/state/lumae/current-flavor"
  local flavor = "dusk"
  if vim.fn.filereadable(state) == 1 then
    local first = (vim.fn.readfile(state) or {})[1]
    if first and first ~= "" then flavor = vim.trim(first) end
  end
  -- Fall back rather than let a missing file abort startup: theme:sync may not
  -- have run yet on a fresh machine.
  local name = "lumae-" .. flavor
  if vim.fn.filereadable(vim.fn.stdpath "config" .. "/colors/" .. name .. ".lua") == 1 then return name end
  return nil
end

---@type LazySpec
return {
  "AstroNvim/astroui",
  ---@type AstroUIOpts
  opts = {
    -- change colorscheme
    colorscheme = lumae_colorscheme(),
    -- AstroUI allows you to easily modify highlight groups easily for any and all colorschemes
    highlights = {
      init = { -- this table overrides highlights in all themes
        -- Normal = { bg = "#000000" },
      },
      astrodark = { -- a table of overrides/changes when applying the astrotheme theme
        -- Normal = { bg = "#000000" },
      },
    },
    -- Icons can be configured throughout the interface
    icons = {
      -- configure the loading of the lsp in the status line
      LSPLoading1 = "⠋",
      LSPLoading2 = "⠙",
      LSPLoading3 = "⠹",
      LSPLoading4 = "⠸",
      LSPLoading5 = "⠼",
      LSPLoading6 = "⠴",
      LSPLoading7 = "⠦",
      LSPLoading8 = "⠧",
      LSPLoading9 = "⠇",
      LSPLoading10 = "⠏",
      MotionHop = "",
      AI = "",
    },
  },
}
